### ISSUE TITLE
Weiße Seite

### ISSUE THREAD

**Issue by DO1JLR** [chaostreff-flensburg/digital-signage#3]
Beim Drucken werden zwei Seiten gedruckt: Eine ist komplett weiß!

**Comment by roikiermedia** [comment]
Hej, kannst du mir einmal sagen unter welchem Browser & OS und bei welchem Layout? Meist kommt es dazu wenn ein Layout Elemente beinhaltet die nicht absolut positioniert sind und diese dann overflowen auf die nächste Seite, dann aber hidden sind.  
P.s. Um den PR #2 kümmere ich mich morgen.

**Comment by DO1JLR** [comment]
Getestet mit dem 34c3 Design unter:

|Browser|Version|
|-----|----|
|Mozilla Firefox 57.0.2|Arch Linux|
|Mozilla Firefox 52.5.2|Debian Sid|

@roikiermedia

**Comment by DO1JLR** [comment]
> P.s. Um den PR #2 kümmere ich mich morgen.

Habs gerade gelesen. 

Wann genau meintest du?

**Comment by scammo** [comment]
Geschlossen weil neuer Software Stand im main :)
